export default {
  image: ['jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg', 'webp', 'heic', 'tiff', 'raw', 'odg', 'eps'],
  audio: ['mp3', 'wav', 'ogg', 'wma', 'aac', 'aif', 'flac'],
  video: ['mp4', 'avi', 'mov', 'webm', 'wmv'],
  doc: ['doc', 'docx', 'odt', 'pages', 'txt', 'tex', 'md', 'mdx'],
  spreadsheet: ['xlr', 'xls', 'xlsx', 'csv', 'numbers'],
  presentation: ['ppt', 'pptx', 'pps', 'odp', 'key'],
  contact: ['contact', 'vcard', 'vcf'],
  archive: ['zip', 'rar', '7z', 'tar', 'gz', 'bz2'],
  bin: ['exe', 'app', 'jar', 'run', 'ipa', 'bin', 'apk', 'msi', 'deb', 'dmg'],
  font: ['woff', 'woff2', 'otf', 'ttf', 'eot'],
  code: [
    'c',
    'cpp',
    'cs',
    'css',
    'go',
    'h',
    'html',
    'java',
    'js',
    'json',
    'jsx',
    'kt',
    'lua',
    'php',
    'py',
    'r',
    'rb',
    'rs',
    'sass',
    'scala',
    'scss',
    'sh',
    'swift',
    'ts',
    'tsx',
    'vb',
    'vue',
    'xml',
    'yaml',
    'yml',
  ],
}
