export default {
  image: [
    'jpg',
    'jpeg',
    'png',
    'gif',
    'bmp',
    'svg',
    'psd',
    'heic',
    'tiff',
    'raw',
  ],
  audio: ['mp3', 'wav', 'ogg', 'wma', 'aac', 'aif', 'flac'],
  video: ['mp4', 'avi', 'mov', 'wmv', 'flv', 'mkv'],
  doc: ['doc', 'docx', 'odt', 'pages', 'rtf', 'txt', 'tex', 'md', 'mdx'],
  spreadsheet: ['xlr', 'xls', 'xlsx', 'numbers'],
  presentation: ['ppt', 'pptx', 'odp', 'key'],
  zip: ['zip', 'rar', '7z', 'tar', 'gz', 'bz2'],
  bin: ['exe', 'app', 'jar', 'run', 'ipa', 'bin', 'apk'],
  fonts: ['woff', 'woff2', 'otf', 'ttf'],
  code: [
    'html',
    'htm',
    'css',
    'sass',
    'scss',
    'js',
    'ts',
    'tsx',
    'vue',
    'php',
    'py',
    'java',
    'c',
    'cpp',
    'cs',
    'rb',
    'rs',
    'sh',
    'swift',
    'vb',
    'xml',
    'json',
    'yaml',
    'yml',
  ],
}
